# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = EMPLOYE.o VOITURE.o faux.o
LINKOBJ  = EMPLOYE.o VOITURE.o faux.o
LIBS     = -L"C:/Users/LENOVO/Dev-Cpp/MinGW64/lib" -L"C:/Users/LENOVO/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/LENOVO/Dev-Cpp/MinGW64/include" -I"C:/Users/LENOVO/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/LENOVO/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/LENOVO/Dev-Cpp/MinGW64/include" -I"C:/Users/LENOVO/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/LENOVO/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/LENOVO/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

EMPLOYE.o: EMPLOYE.c
	$(CC) -c EMPLOYE.c -o EMPLOYE.o $(CFLAGS)

VOITURE.o: VOITURE.c
	$(CC) -c VOITURE.c -o VOITURE.o $(CFLAGS)

faux.o: faux.c
	$(CC) -c faux.c -o faux.o $(CFLAGS)
